#!/usr/bin/env bash
# PS: I couldn't complete code because of I couldn't get connect your server --- It is throwing errors are connection gone --- request timed out. 
# If you can provide any other server which I can connect .. I can complete this task. Thank you. 
set -e 

function connect_to_ftp_server()
{
	
	# return status of ftp server connection
	# if any error then it will stop program to go furhter. 
}

function get_configuaration()
{
	# read password and user name from config file
}

function checkingfileexitst()
{

}

function checkingFilePermissions()
{

}

function ReadFileAndGetFile
{
	checkingfileexitst
	checkingFilePermissions

}


function parserCommandLineInput()
{

}

function main()
{
	get_configuaration
	connect_to_ftp_server
	readfile "$?"
}